plugins {
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':client')
    implementation 'org.testng:testng:7.5'
    testImplementation 'org.testng:testng:7.5'
}

sourceSets {
    main {
        runtimeClasspath += test.output
    }
}

test {
    useTestNG() {
        suites 'src/test/resources/testng.xml'
    }
}

jar {
    manifest {
        attributes 'Main-Class': 'org.example.sftpclient.runner.TestRunner'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    from sourceSets.test.output
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
